site_name: Cluster API driver for Magnum
theme:
  name: material
  features:
    - navigation.tracking
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - literate-nav:
      nav_file: SUMMARY.md
