[tool.poetry]
name = "magnum-cluster-api"
version = "0.0.0"
description = "Cluster API driver for Magnum"
authors = ["Mohammed Naser <mnaser@vexxhost.com>"]
readme = "README.md"
packages = [{include = "magnum_cluster_api"}]

[tool.poetry.dependencies]
python = "^3.8"
pykube-ng = "^22.9.0"
click = "*"
requests = "*"

[build-system]
requires = ["setuptools", "poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
magnum-cluster-api-image-builder = "magnum_cluster_api.cmd.image_builder:main"

[tool.poetry.plugins."magnum.drivers"]
"k8s_cluster_api_ubuntu_focal" = "magnum_cluster_api.driver:UbuntuFocalDriver"
